#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMAInfrastructure.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PMA_TEST")]
	public partial class ProjectDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMEMBER(MEMBER instance);
    partial void UpdateMEMBER(MEMBER instance);
    partial void DeleteMEMBER(MEMBER instance);
    partial void InsertPROJECT(PROJECT instance);
    partial void UpdatePROJECT(PROJECT instance);
    partial void DeletePROJECT(PROJECT instance);
    #endregion
		
		public ProjectDataDataContext() : 
				base(global::PMAInfrastructure.Properties.Settings.Default.PMA_TESTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MEMBER> MEMBERs
		{
			get
			{
				return this.GetTable<MEMBER>();
			}
		}
		
		public System.Data.Linq.Table<PROJECT> PROJECTs
		{
			get
			{
				return this.GetTable<PROJECT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fcn_GetProjects", IsComposable=true)]
		public IQueryable<fcn_GetProjectsResult> fcn_GetProjects()
		{
			return this.CreateMethodCallQuery<fcn_GetProjectsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fcn_GetProjectsByOwnerName", IsComposable=true)]
		public IQueryable<fcn_GetProjectsByOwnerNameResult> fcn_GetProjectsByOwnerName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(30)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(40)")] string lastName)
		{
			return this.CreateMethodCallQuery<fcn_GetProjectsByOwnerNameResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fcn_GetProjectsByName", IsComposable=true)]
		public IQueryable<fcn_GetProjectsByNameResult> fcn_GetProjectsByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name)
		{
			return this.CreateMethodCallQuery<fcn_GetProjectsByNameResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MEMBER")]
	public partial class MEMBER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MEMBER_ID;
		
		private string _MEMBER_LAST_NAME;
		
		private string _MEMBER_FIRST_NAME;
		
		private string _MEMBER_ADR;
		
		private string _MEMBER_POSTAL_CODE;
		
		private string _MEMBER_CITY;
		
		private System.DateTime _MEMBER_BIRTHDATE;
		
		private string _MEMBER_TEL;
		
		private string _MEMBER_MAIL_PRO;
		
		private string _MEMBER_MAIL_PERSO;
		
		private EntitySet<PROJECT> _PROJECTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMEMBER_IDChanging(int value);
    partial void OnMEMBER_IDChanged();
    partial void OnMEMBER_LAST_NAMEChanging(string value);
    partial void OnMEMBER_LAST_NAMEChanged();
    partial void OnMEMBER_FIRST_NAMEChanging(string value);
    partial void OnMEMBER_FIRST_NAMEChanged();
    partial void OnMEMBER_ADRChanging(string value);
    partial void OnMEMBER_ADRChanged();
    partial void OnMEMBER_POSTAL_CODEChanging(string value);
    partial void OnMEMBER_POSTAL_CODEChanged();
    partial void OnMEMBER_CITYChanging(string value);
    partial void OnMEMBER_CITYChanged();
    partial void OnMEMBER_BIRTHDATEChanging(System.DateTime value);
    partial void OnMEMBER_BIRTHDATEChanged();
    partial void OnMEMBER_TELChanging(string value);
    partial void OnMEMBER_TELChanged();
    partial void OnMEMBER_MAIL_PROChanging(string value);
    partial void OnMEMBER_MAIL_PROChanged();
    partial void OnMEMBER_MAIL_PERSOChanging(string value);
    partial void OnMEMBER_MAIL_PERSOChanged();
    #endregion
		
		public MEMBER()
		{
			this._PROJECTs = new EntitySet<PROJECT>(new Action<PROJECT>(this.attach_PROJECTs), new Action<PROJECT>(this.detach_PROJECTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_LAST_NAME", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string MEMBER_LAST_NAME
		{
			get
			{
				return this._MEMBER_LAST_NAME;
			}
			set
			{
				if ((this._MEMBER_LAST_NAME != value))
				{
					this.OnMEMBER_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_LAST_NAME = value;
					this.SendPropertyChanged("MEMBER_LAST_NAME");
					this.OnMEMBER_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_FIRST_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MEMBER_FIRST_NAME
		{
			get
			{
				return this._MEMBER_FIRST_NAME;
			}
			set
			{
				if ((this._MEMBER_FIRST_NAME != value))
				{
					this.OnMEMBER_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_FIRST_NAME = value;
					this.SendPropertyChanged("MEMBER_FIRST_NAME");
					this.OnMEMBER_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_ADR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MEMBER_ADR
		{
			get
			{
				return this._MEMBER_ADR;
			}
			set
			{
				if ((this._MEMBER_ADR != value))
				{
					this.OnMEMBER_ADRChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ADR = value;
					this.SendPropertyChanged("MEMBER_ADR");
					this.OnMEMBER_ADRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_POSTAL_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MEMBER_POSTAL_CODE
		{
			get
			{
				return this._MEMBER_POSTAL_CODE;
			}
			set
			{
				if ((this._MEMBER_POSTAL_CODE != value))
				{
					this.OnMEMBER_POSTAL_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_POSTAL_CODE = value;
					this.SendPropertyChanged("MEMBER_POSTAL_CODE");
					this.OnMEMBER_POSTAL_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_CITY", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MEMBER_CITY
		{
			get
			{
				return this._MEMBER_CITY;
			}
			set
			{
				if ((this._MEMBER_CITY != value))
				{
					this.OnMEMBER_CITYChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_CITY = value;
					this.SendPropertyChanged("MEMBER_CITY");
					this.OnMEMBER_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_BIRTHDATE", DbType="DateTime NOT NULL")]
		public System.DateTime MEMBER_BIRTHDATE
		{
			get
			{
				return this._MEMBER_BIRTHDATE;
			}
			set
			{
				if ((this._MEMBER_BIRTHDATE != value))
				{
					this.OnMEMBER_BIRTHDATEChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_BIRTHDATE = value;
					this.SendPropertyChanged("MEMBER_BIRTHDATE");
					this.OnMEMBER_BIRTHDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_TEL", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MEMBER_TEL
		{
			get
			{
				return this._MEMBER_TEL;
			}
			set
			{
				if ((this._MEMBER_TEL != value))
				{
					this.OnMEMBER_TELChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_TEL = value;
					this.SendPropertyChanged("MEMBER_TEL");
					this.OnMEMBER_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_MAIL_PRO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string MEMBER_MAIL_PRO
		{
			get
			{
				return this._MEMBER_MAIL_PRO;
			}
			set
			{
				if ((this._MEMBER_MAIL_PRO != value))
				{
					this.OnMEMBER_MAIL_PROChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_MAIL_PRO = value;
					this.SendPropertyChanged("MEMBER_MAIL_PRO");
					this.OnMEMBER_MAIL_PROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_MAIL_PERSO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string MEMBER_MAIL_PERSO
		{
			get
			{
				return this._MEMBER_MAIL_PERSO;
			}
			set
			{
				if ((this._MEMBER_MAIL_PERSO != value))
				{
					this.OnMEMBER_MAIL_PERSOChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_MAIL_PERSO = value;
					this.SendPropertyChanged("MEMBER_MAIL_PERSO");
					this.OnMEMBER_MAIL_PERSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBER_PROJECT", Storage="_PROJECTs", ThisKey="MEMBER_ID", OtherKey="PROJECT_OWNER_ID")]
		public EntitySet<PROJECT> PROJECTs
		{
			get
			{
				return this._PROJECTs;
			}
			set
			{
				this._PROJECTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PROJECTs(PROJECT entity)
		{
			this.SendPropertyChanging();
			entity.MEMBER = this;
		}
		
		private void detach_PROJECTs(PROJECT entity)
		{
			this.SendPropertyChanging();
			entity.MEMBER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROJECT")]
	public partial class PROJECT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PROJECT_ID;
		
		private string _PROJECT_NAME;
		
		private System.DateTime _PROJECT_START_DATE;
		
		private System.DateTime _PROJECT_END_DATE;
		
		private int _PROJECT_OWNER_ID;
		
		private EntityRef<MEMBER> _MEMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPROJECT_IDChanging(int value);
    partial void OnPROJECT_IDChanged();
    partial void OnPROJECT_NAMEChanging(string value);
    partial void OnPROJECT_NAMEChanged();
    partial void OnPROJECT_START_DATEChanging(System.DateTime value);
    partial void OnPROJECT_START_DATEChanged();
    partial void OnPROJECT_END_DATEChanging(System.DateTime value);
    partial void OnPROJECT_END_DATEChanged();
    partial void OnPROJECT_OWNER_IDChanging(int value);
    partial void OnPROJECT_OWNER_IDChanged();
    #endregion
		
		public PROJECT()
		{
			this._MEMBER = default(EntityRef<MEMBER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PROJECT_ID
		{
			get
			{
				return this._PROJECT_ID;
			}
			set
			{
				if ((this._PROJECT_ID != value))
				{
					this.OnPROJECT_IDChanging(value);
					this.SendPropertyChanging();
					this._PROJECT_ID = value;
					this.SendPropertyChanged("PROJECT_ID");
					this.OnPROJECT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT_NAME", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string PROJECT_NAME
		{
			get
			{
				return this._PROJECT_NAME;
			}
			set
			{
				if ((this._PROJECT_NAME != value))
				{
					this.OnPROJECT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PROJECT_NAME = value;
					this.SendPropertyChanged("PROJECT_NAME");
					this.OnPROJECT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT_START_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime PROJECT_START_DATE
		{
			get
			{
				return this._PROJECT_START_DATE;
			}
			set
			{
				if ((this._PROJECT_START_DATE != value))
				{
					this.OnPROJECT_START_DATEChanging(value);
					this.SendPropertyChanging();
					this._PROJECT_START_DATE = value;
					this.SendPropertyChanged("PROJECT_START_DATE");
					this.OnPROJECT_START_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT_END_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime PROJECT_END_DATE
		{
			get
			{
				return this._PROJECT_END_DATE;
			}
			set
			{
				if ((this._PROJECT_END_DATE != value))
				{
					this.OnPROJECT_END_DATEChanging(value);
					this.SendPropertyChanging();
					this._PROJECT_END_DATE = value;
					this.SendPropertyChanged("PROJECT_END_DATE");
					this.OnPROJECT_END_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT_OWNER_ID", DbType="Int NOT NULL")]
		public int PROJECT_OWNER_ID
		{
			get
			{
				return this._PROJECT_OWNER_ID;
			}
			set
			{
				if ((this._PROJECT_OWNER_ID != value))
				{
					if (this._MEMBER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPROJECT_OWNER_IDChanging(value);
					this.SendPropertyChanging();
					this._PROJECT_OWNER_ID = value;
					this.SendPropertyChanged("PROJECT_OWNER_ID");
					this.OnPROJECT_OWNER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBER_PROJECT", Storage="_MEMBER", ThisKey="PROJECT_OWNER_ID", OtherKey="MEMBER_ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public MEMBER MEMBER
		{
			get
			{
				return this._MEMBER.Entity;
			}
			set
			{
				MEMBER previousValue = this._MEMBER.Entity;
				if (((previousValue != value) 
							|| (this._MEMBER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MEMBER.Entity = null;
						previousValue.PROJECTs.Remove(this);
					}
					this._MEMBER.Entity = value;
					if ((value != null))
					{
						value.PROJECTs.Add(this);
						this._PROJECT_OWNER_ID = value.MEMBER_ID;
					}
					else
					{
						this._PROJECT_OWNER_ID = default(int);
					}
					this.SendPropertyChanged("MEMBER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class fcn_GetProjectsResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private int _OwnerId;
		
		private string _OwnerFirstName;
		
		private string _OwnerLastName;
		
		public fcn_GetProjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerId", DbType="Int NOT NULL")]
		public int OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					this._OwnerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerFirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string OwnerFirstName
		{
			get
			{
				return this._OwnerFirstName;
			}
			set
			{
				if ((this._OwnerFirstName != value))
				{
					this._OwnerFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerLastName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string OwnerLastName
		{
			get
			{
				return this._OwnerLastName;
			}
			set
			{
				if ((this._OwnerLastName != value))
				{
					this._OwnerLastName = value;
				}
			}
		}
	}
	
	public partial class fcn_GetProjectsByOwnerNameResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private int _OwnerId;
		
		private string _OwnerFirstName;
		
		private string _OwnerLastName;
		
		public fcn_GetProjectsByOwnerNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerId", DbType="Int NOT NULL")]
		public int OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					this._OwnerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerFirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string OwnerFirstName
		{
			get
			{
				return this._OwnerFirstName;
			}
			set
			{
				if ((this._OwnerFirstName != value))
				{
					this._OwnerFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerLastName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string OwnerLastName
		{
			get
			{
				return this._OwnerLastName;
			}
			set
			{
				if ((this._OwnerLastName != value))
				{
					this._OwnerLastName = value;
				}
			}
		}
	}
	
	public partial class fcn_GetProjectsByNameResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private int _OwnerId;
		
		private string _OwnerFirstName;
		
		private string _OwnerLastName;
		
		public fcn_GetProjectsByNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerId", DbType="Int NOT NULL")]
		public int OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					this._OwnerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerFirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string OwnerFirstName
		{
			get
			{
				return this._OwnerFirstName;
			}
			set
			{
				if ((this._OwnerFirstName != value))
				{
					this._OwnerFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerLastName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string OwnerLastName
		{
			get
			{
				return this._OwnerLastName;
			}
			set
			{
				if ((this._OwnerLastName != value))
				{
					this._OwnerLastName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
