USE [PMA_TEST]
GO

---------------------------------------------------------------------
-- TEMP: DROP TABLE FOR TESTS.
---------------------------------------------------------------------
DROP TABLE TASK
GO

DROP TABLE ASSIGNMENT
GO

DROP TABLE PROJECT
GO

DROP TABLE MEMBER
GO

---------------------------------------------------------------------
-- TABLE MEMBER
---------------------------------------------------------------------
IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MEMBER]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE MEMBER
	(
		MEMBER_ID			INT				NOT NULL IDENTITY(1,1),
		MEMBER_LAST_NAME	VARCHAR(40)		NOT NULL,
		MEMBER_FIRST_NAME	VARCHAR(30)		NOT NULL,
		MEMBER_ADR			VARCHAR(100)	NOT NULL,
		MEMBER_POSTAL_CODE	VARCHAR(10)		NOT NULL,
		MEMBER_CITY			VARCHAR(50)		NOT NULL,
		MEMBER_BIRTHDATE	DATETIME		NOT NULL,
		MEMBER_TEL			VARCHAR(20)		NOT NULL,
		MEMBER_MAIL_PRO		VARCHAR(80)		NOT NULL,
		MEMBER_MAIL_PERSO	VARCHAR(80)		NOT NULL,
	)
	
	ALTER TABLE MEMBER
	ADD CONSTRAINT	PK_MBM_MEMBER_ID	PRIMARY KEY (MEMBER_ID)
END
GO

---------------------------------------------------------------------
-- TABLE PROJECT
---------------------------------------------------------------------
IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[PROJECT]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE PROJECT
	(
		PROJECT_ID			INT			NOT NULL IDENTITY(1,1),
		PROJECT_NAME		VARCHAR(80)	NOT NULL,
		PROJECT_START_DATE	DATETIME	NOT NULL,
		PROJECT_END_DATE	DATETIME	NOT NULL,
		PROJECT_OWNER_ID	INT										-- To be modified when creating MEMBER_ASSIGNMENT TABLE.
		--PROJECT_STATUS_ID	INT			NOT NULL					-- To add with a table "PROJECT_STATUS"
	)

	ALTER TABLE PROJECT
		ADD CONSTRAINT	PK_PRJ_PROJECT_ID	PRIMARY KEY (PROJECT_ID)

	ALTER TABLE PROJECT
		ADD CONSTRAINT	FK_PRJ_PROJECT_OWNER_ID 
		FOREIGN KEY (PROJECT_OWNER_ID)									-- To be modified when creating MEMBER_ASSIGNMENT TABLE.
		REFERENCES MEMBER(MEMBER_ID)  ON DELETE SET NULL
END
GO

---------------------------------------------------------------------
-- TABLE ASSIGNMENT
---------------------------------------------------------------------
IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ASSIGNMENT]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE ASSIGNMENT
	(
		ASSIGNMENT_ID			INT				NOT NULL IDENTITY(1,1),
		MEMBER_ID				INT				NOT NULL,	
		PROJECT_ID				INT				NOT NULL,
		ASSIGNMENT_NAME			VARCHAR(100)	NOT NULL,
		ASSIGNMENT_START_DATE	DATETIME		NOT NULL,
		ASSIGNMENT_END_DATE		DATETIME		DEFAULT '99991231'
	)

	ALTER TABLE ASSIGNMENT
		ADD CONSTRAINT	PK_ASG_ASSIGNMENT_ID	PRIMARY KEY (ASSIGNMENT_ID)
	
	ALTER TABLE ASSIGNMENT
		ADD CONSTRAINT	FK_ASG_MEMBER_ID 
		FOREIGN KEY (MEMBER_ID)									
		REFERENCES MEMBER(MEMBER_ID)  	ON DELETE CASCADE
		
	ALTER TABLE ASSIGNMENT
		ADD CONSTRAINT	FK_ASG_PROJECT_ID 
		FOREIGN KEY (PROJECT_ID)									
		REFERENCES PROJECT(PROJECT_ID)  ON DELETE CASCADE
END
GO

---------------------------------------------------------------------
-- TABLE TASK
---------------------------------------------------------------------
IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[TASK]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE TASK
	(
		TASK_ID				INT				NOT NULL IDENTITY(1,1),
		ASSIGNMENT_ID		INT				NOT NULL,
		TASK_NAME			VARCHAR(100)	NOT NULL,
		TASK_START_DATE		DATETIME		NOT NULL,
		TASK_END_DATE		DATETIME		DEFAULT '99991231'
	)

	ALTER TABLE TASK
		ADD CONSTRAINT	PK_TSK_TASK_ID	PRIMARY KEY (TASK_ID)
	
	ALTER TABLE TASK
		ADD CONSTRAINT	FK_TSK_ASSIGNMENT_ID 
		FOREIGN KEY (ASSIGNMENT_ID)									
		REFERENCES ASSIGNMENT(ASSIGNMENT_ID)  ON DELETE CASCADE
END
GO
