USE [PMA_TEST]
GO

IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MEMBER]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE MEMBER
	(
		MEMBER_ID			INT				NOT NULL IDENTITY(1,1),
		MEMBER_LAST_NAME	VARCHAR(40)		NOT NULL,
		MEMBER_FIRST_NAME	VARCHAR(30)		NOT NULL,
		MEMBER_ADR			VARCHAR(100)	NOT NULL,
		MEMBER_POSTAL_CODE	VARCHAR(10)		NOT NULL,
		MEMBER_CITY			VARCHAR(50)		NOT NULL,
		MEMBER_BIRTHDATE	DATETIME		NOT NULL,
		MEMBER_TEL			VARCHAR(20)		NOT NULL,
		MEMBER_MAIL_PRO		VARCHAR(80)		NOT NULL,
		MEMBER_MAIL_PERSO	VARCHAR(80)		NOT NULL,
	)
	
	ALTER TABLE MEMBER
	ADD CONSTRAINT	PK_MEMBER_ID	PRIMARY KEY (MEMBER_ID)
END
GO

IF NOT EXISTS (
	SELECT 1 FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[PROJECT]') 
	AND type in (N'U')
)
BEGIN
	CREATE TABLE PROJECT
	(
		PROJECT_ID			INT			NOT NULL IDENTITY(1,1),
		PROJECT_NAME		VARCHAR(80)	NOT NULL,
		PROJECT_START_DATE	DATETIME	NOT NULL,
		PROJECT_END_DATE	DATETIME	NOT NULL,
		PROJECT_OWNER_ID	INT			NOT NULL	DEFAULT 0			-- To be modified when creating MEMBER_ASSIGNMENT TABLE.
		--PROJECT_STATUS_ID	INT			NOT NULL						-- To add with a table "PROJECT_STATUS"
	)

	ALTER TABLE PROJECT
		ADD CONSTRAINT	PK_PROJECT_ID	PRIMARY KEY (PROJECT_ID)

	ALTER TABLE PROJECT
		ADD CONSTRAINT	FK_PROJECT_OWNER_ID 
		FOREIGN KEY (PROJECT_OWNER_ID)									-- To be modified when creating MEMBER_ASSIGNMENT TABLE.
		REFERENCES MEMBER(MEMBER_ID)  ON DELETE CASCADE
END
GO
